<?php

/**
 * @file
 * Contains log.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the log module.
    case 'help.page.log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Log entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function log_theme() {
  $theme = [
    'log' => array(
      'render element' => 'elements',
    ),
    'log_add_list' => array(
      'variables' => array('content' => NULL),
    ),
  ];

  return $theme;
}
