# Schema for the configuration files of the log module.
log.type.*:
  type: config_entity
  label: 'Log type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    name_pattern:
      type: string
      label: 'Pattern for auto-generating the log name, using tokens.'
    workflow:
      type: string
      label: 'Workflow'
    new_revision:
      type: boolean
      label: 'Create new revision'

condition.plugin.log_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string

views.sort.log_timestamp_id:
  type: views_sort
  label: 'Log Timestamp Id'
  mapping:
    timestamp_order:
      type: string
      label: 'Timestamp order'
    id_order:
      type: string
      label: 'ID order'
    granularity:
      type: string
      label: 'Granularity'
