<?php

/**
 * @file
 * Log Plan
 * A planning module that utilizes log entities.
 */

/****************************************************************
 * Drupal hooks
 * **************************************************************/

/**
 * Implements hook_permission().
 */
function log_plan_permission() {
  $perms = array(
    'view log plan' => array(
      'title' => t('View log plan'),
      'description' => t('Allow access to the log plan View at /plan'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_admin_paths().
 */
function log_plan_admin_paths() {

  // Display log paths with the admin theme, if specified.
  if (variable_get('log_admin_theme', TRUE)) {
    $paths = array(
      'plan*' => TRUE,
    );
    return $paths;
  }
}

/***************************************************************
 * Views hooks
 * *************************************************************/

/**
 * Implements hook_views_api().
 */
function log_plan_views_api() {
  return array('version' => 3);
}